<?php
// All countries
// length 252
$countries_list = array(
    "AF" => array("name" => "Afghanistan", "phone" => "93", "continent" => "Asia", "continent_code" => "AS", "id" => "1"),
    "AX" => array("name" => "Aland Islands", "phone" => "358", "continent" => "Europe", "continent_code" => "EU", "id" => "2"),
    "AL" => array("name" => "Albania", "phone" => "355", "continent" => "Europe", "continent_code" => "EU", "id" => "3"),
    "DZ" => array("name" => "Algeria", "phone" => "213", "continent" => "Africa", "continent_code" => "AF", "id" => "4"),
    "AS" => array("name" => "American Samoa", "phone" => "1684", "continent" => "Oceania", "continent_code" => "OC", "id" => "5"),
    "AD" => array("name" => "Andorra", "phone" => "376", "continent" => "Europe", "continent_code" => "EU", "id" => "6"),
    "AO" => array("name" => "Angola", "phone" => "244", "continent" => "Africa", "continent_code" => "AF", "id" => "7"),
    "AI" => array("name" => "Anguilla", "phone" => "1264", "continent" => "North America", "continent_code" => "NA", "id" => "8"),
    "AQ" => array("name" => "Antarctica", "phone" => "672", "continent" => "Antarctica", "continent_code" => "AN", "id" => "9"),
    "AG" => array("name" => "Antigua and Barbuda", "phone" => "1268", "continent" => "North America", "continent_code" => "NA", "id" => "10"),
    "AR" => array("name" => "Argentina", "phone" => "54", "continent" => "South America", "continent_code" => "SA", "id" => "11"),
    "AM" => array("name" => "Armenia", "phone" => "374", "continent" => "Asia", "continent_code" => "AS", "id" => "12"),
    "AW" => array("name" => "Aruba", "phone" => "297", "continent" => "North America", "continent_code" => "NA", "id" => "13"),
    "AU" => array("name" => "Australia", "phone" => "61", "continent" => "Oceania", "continent_code" => "OC", "id" => "14"),
    "AT" => array("name" => "Austria", "phone" => "43", "continent" => "Europe", "continent_code" => "EU", "id" => "15"),
    "AZ" => array("name" => "Azerbaijan", "phone" => "994", "continent" => "Asia", "continent_code" => "AS", "id" => "16"),
    "BS" => array("name" => "Bahamas", "phone" => "1242", "continent" => "North America", "continent_code" => "NA", "id" => "17"),
    "BH" => array("name" => "Bahrain", "phone" => "973", "continent" => "Asia", "continent_code" => "AS", "id" => "18"),
    "BD" => array("name" => "Bangladesh", "phone" => "880", "continent" => "Asia", "continent_code" => "AS", "id" => "19"),
    "BB" => array("name" => "Barbados", "phone" => "1246", "continent" => "North America", "continent_code" => "NA", "id" => "20"),
    "BY" => array("name" => "Belarus", "phone" => "375", "continent" => "Europe", "continent_code" => "EU", "id" => "21"),
    "BE" => array("name" => "Belgium", "phone" => "32", "continent" => "Europe", "continent_code" => "EU", "id" => "22"),
    "BZ" => array("name" => "Belize", "phone" => "501", "continent" => "North America", "continent_code" => "NA", "id" => "23"),
    "BJ" => array("name" => "Benin", "phone" => "229", "continent" => "Africa", "continent_code" => "AF", "id" => "24"),
    "BM" => array("name" => "Bermuda", "phone" => "1441", "continent" => "North America", "continent_code" => "NA", "id" => "25"),
    "BT" => array("name" => "Bhutan", "phone" => "975", "continent" => "Asia", "continent_code" => "AS", "id" => "26"),
    "BO" => array("name" => "Bolivia", "phone" => "591", "continent" => "South America", "continent_code" => "SA", "id" => "27"),
    "BQ" => array("name" => "Bonaire, Sint Eustatius and Saba", "phone" => "599", "continent" => "North America", "continent_code" => "NA", "id" => "28"),
    "BA" => array("name" => "Bosnia and Herzegovina", "phone" => "387", "continent" => "Europe", "continent_code" => "EU", "id" => "29"),
    "BW" => array("name" => "Botswana", "phone" => "267", "continent" => "Africa", "continent_code" => "AF", "id" => "30"),
    "BV" => array("name" => "Bouvet Island", "phone" => "55", "continent" => "Antarctica", "continent_code" => "AN", "id" => "31"),
    "BR" => array("name" => "Brazil", "phone" => "55", "continent" => "South America", "continent_code" => "SA", "id" => "32"),
    "IO" => array("name" => "British Indian Ocean Territory", "phone" => "246", "continent" => "Asia", "continent_code" => "AS", "id" => "33"),
    "BN" => array("name" => "Brunei Darussalam", "phone" => "673", "continent" => "Asia", "continent_code" => "AS", "id" => "34"),
    "BG" => array("name" => "Bulgaria", "phone" => "359", "continent" => "Europe", "continent_code" => "EU", "id" => "35"),
    "BF" => array("name" => "Burkina Faso", "phone" => "226", "continent" => "Africa", "continent_code" => "AF", "id" => "36"),
    "BI" => array("name" => "Burundi", "phone" => "257", "continent" => "Africa", "continent_code" => "AF", "id" => "37"),
    "KH" => array("name" => "Cambodia", "phone" => "855", "continent" => "Asia", "continent_code" => "AS", "id" => "38"),
    "CM" => array("name" => "Cameroon", "phone" => "237", "continent" => "Africa", "continent_code" => "AF", "id" => "39"),
    "CA" => array("name" => "Canada", "phone" => "1", "continent" => "North America", "continent_code" => "NA", "id" => "40"),
    "CV" => array("name" => "Cape Verde", "phone" => "238", "continent" => "Africa", "continent_code" => "AF", "id" => "41"),
    "KY" => array("name" => "Cayman Islands", "phone" => "1345", "continent" => "North America", "continent_code" => "NA", "id" => "42"),
    "CF" => array("name" => "Central African Republic", "phone" => "236", "continent" => "Africa", "continent_code" => "AF", "id" => "43"),
    "TD" => array("name" => "Chad", "phone" => "235", "continent" => "Africa", "continent_code" => "AF", "id" => "44"),
    "CL" => array("name" => "Chile", "phone" => "56", "continent" => "South America", "continent_code" => "SA", "id" => "45"),
    "CN" => array("name" => "China", "phone" => "86", "continent" => "Asia", "continent_code" => "AS", "id" => "46"),
    "CX" => array("name" => "Christmas Island", "phone" => "61", "continent" => "Asia", "continent_code" => "AS", "id" => "47"),
    "CC" => array("name" => "Cocos (Keeling) Islands", "phone" => "672", "continent" => "Asia", "continent_code" => "AS", "id" => "48"),
    "CO" => array("name" => "Colombia", "phone" => "57", "continent" => "South America", "continent_code" => "SA", "id" => "49"),
    "KM" => array("name" => "Comoros", "phone" => "269", "continent" => "Africa", "continent_code" => "AF", "id" => "50"),
    "CG" => array("name" => "Congo", "phone" => "242", "continent" => "Africa", "continent_code" => "AF", "id" => "51"),
    "CD" => array("name" => "Congo, Democratic Republic of the Congo", "phone" => "242", "continent" => "Africa", "continent_code" => "AF", "id" => "52"),
    "CK" => array("name" => "Cook Islands", "phone" => "682", "continent" => "Oceania", "continent_code" => "OC", "id" => "53"),
    "CR" => array("name" => "Costa Rica", "phone" => "506", "continent" => "North America", "continent_code" => "NA", "id" => "54"),
    "CI" => array("name" => "Cote D'Ivoire", "phone" => "225", "continent" => "Africa", "continent_code" => "AF", "id" => "55"),
    "HR" => array("name" => "Croatia", "phone" => "385", "continent" => "Europe", "continent_code" => "EU", "id" => "56"),
    "CU" => array("name" => "Cuba", "phone" => "53", "continent" => "North America", "continent_code" => "NA", "id" => "57"),
    "CW" => array("name" => "Curacao", "phone" => "599", "continent" => "North America", "continent_code" => "NA", "id" => "58"),
    "CY" => array("name" => "Cyprus", "phone" => "357", "continent" => "Asia", "continent_code" => "AS", "id" => "59"),
    "CZ" => array("name" => "Czech Republic", "phone" => "420", "continent" => "Europe", "continent_code" => "EU", "id" => "60"),
    "DK" => array("name" => "Denmark", "phone" => "45", "continent" => "Europe", "continent_code" => "EU", "id" => "61"),
    "DJ" => array("name" => "Djibouti", "phone" => "253", "continent" => "Africa", "continent_code" => "AF", "id" => "62"),
    "DM" => array("name" => "Dominica", "phone" => "1767", "continent" => "North America", "continent_code" => "NA", "id" => "63"),
    "DO" => array("name" => "Dominican Republic", "phone" => "1809", "continent" => "North America", "continent_code" => "NA", "id" => "64"),
    "EC" => array("name" => "Ecuador", "phone" => "593", "continent" => "South America", "continent_code" => "SA", "id" => "65"),
    "EG" => array("name" => "Egypt", "phone" => "20", "continent" => "Africa", "continent_code" => "AF", "id" => "66"),
    "SV" => array("name" => "El Salvador", "phone" => "503", "continent" => "North America", "continent_code" => "NA", "id" => "67"),
    "GQ" => array("name" => "Equatorial Guinea", "phone" => "240", "continent" => "Africa", "continent_code" => "AF", "id" => "68"),
    "ER" => array("name" => "Eritrea", "phone" => "291", "continent" => "Africa", "continent_code" => "AF", "id" => "69"),
    "EE" => array("name" => "Estonia", "phone" => "372", "continent" => "Europe", "continent_code" => "EU", "id" => "70"),
    "ET" => array("name" => "Ethiopia", "phone" => "251", "continent" => "Africa", "continent_code" => "AF", "id" => "71"),
    "FK" => array("name" => "Falkland Islands (Malvinas)", "phone" => "500", "continent" => "South America", "continent_code" => "SA", "id" => "72"),
    "FO" => array("name" => "Faroe Islands", "phone" => "298", "continent" => "Europe", "continent_code" => "EU", "id" => "73"),
    "FJ" => array("name" => "Fiji", "phone" => "679", "continent" => "Oceania", "continent_code" => "OC", "id" => "74"),
    "FI" => array("name" => "Finland", "phone" => "358", "continent" => "Europe", "continent_code" => "EU", "id" => "75"),
    "FR" => array("name" => "France", "phone" => "33", "continent" => "Europe", "continent_code" => "EU", "id" => "76"),
    "GF" => array("name" => "French Guiana", "phone" => "594", "continent" => "South America", "continent_code" => "SA", "id" => "77"),
    "PF" => array("name" => "French Polynesia", "phone" => "689", "continent" => "Oceania", "continent_code" => "OC", "id" => "78"),
    "TF" => array("name" => "French Southern Territories", "phone" => "262", "continent" => "Antarctica", "continent_code" => "AN", "id" => "79"),
    "GA" => array("name" => "Gabon", "phone" => "241", "continent" => "Africa", "continent_code" => "AF", "id" => "80"),
    "GM" => array("name" => "Gambia", "phone" => "220", "continent" => "Africa", "continent_code" => "AF", "id" => "81"),
    "GE" => array("name" => "Georgia", "phone" => "995", "continent" => "Asia", "continent_code" => "AS", "id" => "82"),
    "DE" => array("name" => "Germany", "phone" => "49", "continent" => "Europe", "continent_code" => "EU", "id" => "83"),
    "GH" => array("name" => "Ghana", "phone" => "233", "continent" => "Africa", "continent_code" => "AF", "id" => "84"),
    "GI" => array("name" => "Gibraltar", "phone" => "350", "continent" => "Europe", "continent_code" => "EU", "id" => "85"),
    "GR" => array("name" => "Greece", "phone" => "30", "continent" => "Europe", "continent_code" => "EU", "id" => "86"),
    "GL" => array("name" => "Greenland", "phone" => "299", "continent" => "North America", "continent_code" => "NA", "id" => "87"),
    "GD" => array("name" => "Grenada", "phone" => "1473", "continent" => "North America", "continent_code" => "NA", "id" => "88"),
    "GP" => array("name" => "Guadeloupe", "phone" => "590", "continent" => "North America", "continent_code" => "NA", "id" => "89"),
    "GU" => array("name" => "Guam", "phone" => "1671", "continent" => "Oceania", "continent_code" => "OC", "id" => "90"),
    "GT" => array("name" => "Guatemala", "phone" => "502", "continent" => "North America", "continent_code" => "NA", "id" => "91"),
    "GG" => array("name" => "Guernsey", "phone" => "44", "continent" => "Europe", "continent_code" => "EU", "id" => "92"),
    "GN" => array("name" => "Guinea", "phone" => "224", "continent" => "Africa", "continent_code" => "AF", "id" => "93"),
    "GW" => array("name" => "Guinea-Bissau", "phone" => "245", "continent" => "Africa", "continent_code" => "AF", "id" => "94"),
    "GY" => array("name" => "Guyana", "phone" => "592", "continent" => "South America", "continent_code" => "SA", "id" => "95"),
    "HT" => array("name" => "Haiti", "phone" => "509", "continent" => "North America", "continent_code" => "NA", "id" => "96"),
    "HM" => array("name" => "Heard Island and Mcdonald Islands", "phone" => "0", "continent" => "Antarctica", "continent_code" => "AN", "id" => "97"),
    "VA" => array("name" => "Holy See (Vatican City State)", "phone" => "39", "continent" => "Europe", "continent_code" => "EU", "id" => "98"),
    "HN" => array("name" => "Honduras", "phone" => "504", "continent" => "North America", "continent_code" => "NA", "id" => "99"),
    "HK" => array("name" => "Hong Kong", "phone" => "852", "continent" => "Asia", "continent_code" => "AS", "id" => "100"),
    "HU" => array("name" => "Hungary", "phone" => "36", "continent" => "Europe", "continent_code" => "EU", "id" => "101"),
    "IS" => array("name" => "Iceland", "phone" => "354", "continent" => "Europe", "continent_code" => "EU", "id" => "102"),
    "IN" => array("name" => "India", "phone" => "91", "continent" => "Asia", "continent_code" => "AS", "id" => "103"),
    "ID" => array("name" => "Indonesia", "phone" => "62", "continent" => "Asia", "continent_code" => "AS", "id" => "104"),
    "IR" => array("name" => "Iran, Islamic Republic of", "phone" => "98", "continent" => "Asia", "continent_code" => "AS", "id" => "105"),
    "IQ" => array("name" => "Iraq", "phone" => "964", "continent" => "Asia", "continent_code" => "AS", "id" => "106"),
    "IE" => array("name" => "Ireland", "phone" => "353", "continent" => "Europe", "continent_code" => "EU", "id" => "107"),
    "IM" => array("name" => "Isle of Man", "phone" => "44", "continent" => "Europe", "continent_code" => "EU", "id" => "108"),
    "IL" => array("name" => "Israel", "phone" => "972", "continent" => "Asia", "continent_code" => "AS", "id" => "109"),
    "IT" => array("name" => "Italy", "phone" => "39", "continent" => "Europe", "continent_code" => "EU", "id" => "110"),
    "JM" => array("name" => "Jamaica", "phone" => "1876", "continent" => "North America", "continent_code" => "NA", "id" => "111"),
    "JP" => array("name" => "Japan", "phone" => "81", "continent" => "Asia", "continent_code" => "AS", "id" => "112"),
    "JE" => array("name" => "Jersey", "phone" => "44", "continent" => "Europe", "continent_code" => "EU", "id" => "113"),
    "JO" => array("name" => "Jordan", "phone" => "962", "continent" => "Asia", "continent_code" => "AS", "id" => "114"),
    "KZ" => array("name" => "Kazakhstan", "phone" => "7", "continent" => "Asia", "continent_code" => "AS", "id" => "115"),
    "KE" => array("name" => "Kenya", "phone" => "254", "continent" => "Africa", "continent_code" => "AF", "id" => "116"),
    "KI" => array("name" => "Kiribati", "phone" => "686", "continent" => "Oceania", "continent_code" => "OC", "id" => "117"),
    "KP" => array("name" => "Korea, Democratic People's Republic of", "phone" => "850", "continent" => "Asia", "continent_code" => "AS", "id" => "118"),
    "KR" => array("name" => "Korea, Republic of", "phone" => "82", "continent" => "Asia", "continent_code" => "AS", "id" => "119"),
    "XK" => array("name" => "Kosovo", "phone" => "381", "continent" => "Europe", "continent_code" => "EU", "id" => "120"),
    "KW" => array("name" => "Kuwait", "phone" => "965", "continent" => "Asia", "continent_code" => "AS", "id" => "121"),
    "KG" => array("name" => "Kyrgyzstan", "phone" => "996", "continent" => "Asia", "continent_code" => "AS", "id" => "122"),
    "LA" => array("name" => "Lao People's Democratic Republic", "phone" => "856", "continent" => "Asia", "continent_code" => "AS", "id" => "123"),
    "LV" => array("name" => "Latvia", "phone" => "371", "continent" => "Europe", "continent_code" => "EU", "id" => "124"),
    "LB" => array("name" => "Lebanon", "phone" => "961", "continent" => "Asia", "continent_code" => "AS", "id" => "125"),
    "LS" => array("name" => "Lesotho", "phone" => "266", "continent" => "Africa", "continent_code" => "AF", "id" => "126"),
    "LR" => array("name" => "Liberia", "phone" => "231", "continent" => "Africa", "continent_code" => "AF", "id" => "127"),
    "LY" => array("name" => "Libyan Arab Jamahiriya", "phone" => "218", "continent" => "Africa", "continent_code" => "AF", "id" => "128"),
    "LI" => array("name" => "Liechtenstein", "phone" => "423", "continent" => "Europe", "continent_code" => "EU", "id" => "129"),
    "LT" => array("name" => "Lithuania", "phone" => "370", "continent" => "Europe", "continent_code" => "EU", "id" => "130"),
    "LU" => array("name" => "Luxembourg", "phone" => "352", "continent" => "Europe", "continent_code" => "EU", "id" => "131"),
    "MO" => array("name" => "Macao", "phone" => "853", "continent" => "Asia", "continent_code" => "AS", "id" => "132"),
    "MK" => array("name" => "Macedonia, the Former Yugoslav Republic of", "phone" => "389", "continent" => "Europe", "continent_code" => "EU", "id" => "133"),
    "MG" => array("name" => "Madagascar", "phone" => "261", "continent" => "Africa", "continent_code" => "AF", "id" => "134"),
    "MW" => array("name" => "Malawi", "phone" => "265", "continent" => "Africa", "continent_code" => "AF", "id" => "135"),
    "MY" => array("name" => "Malaysia", "phone" => "60", "continent" => "Asia", "continent_code" => "AS", "id" => "136"),
    "MV" => array("name" => "Maldives", "phone" => "960", "continent" => "Asia", "continent_code" => "AS", "id" => "137"),
    "ML" => array("name" => "Mali", "phone" => "223", "continent" => "Africa", "continent_code" => "AF", "id" => "138"),
    "MT" => array("name" => "Malta", "phone" => "356", "continent" => "Europe", "continent_code" => "EU", "id" => "139"),
    "MH" => array("name" => "Marshall Islands", "phone" => "692", "continent" => "Oceania", "continent_code" => "OC", "id" => "140"),
    "MQ" => array("name" => "Martinique", "phone" => "596", "continent" => "North America", "continent_code" => "NA", "id" => "141"),
    "MR" => array("name" => "Mauritania", "phone" => "222", "continent" => "Africa", "continent_code" => "AF", "id" => "142"),
    "MU" => array("name" => "Mauritius", "phone" => "230", "continent" => "Africa", "continent_code" => "AF", "id" => "143"),
    "YT" => array("name" => "Mayotte", "phone" => "262", "continent" => "Africa", "continent_code" => "AF", "id" => "144"),
    "MX" => array("name" => "Mexico", "phone" => "52", "continent" => "North America", "continent_code" => "NA", "id" => "145"),
    "FM" => array("name" => "Micronesia, Federated States of", "phone" => "691", "continent" => "Oceania", "continent_code" => "OC", "id" => "146"),
    "MD" => array("name" => "Moldova, Republic of", "phone" => "373", "continent" => "Europe", "continent_code" => "EU", "id" => "147"),
    "MC" => array("name" => "Monaco", "phone" => "377", "continent" => "Europe", "continent_code" => "EU", "id" => "148"),
    "MN" => array("name" => "Mongolia", "phone" => "976", "continent" => "Asia", "continent_code" => "AS", "id" => "149"),
    "ME" => array("name" => "Montenegro", "phone" => "382", "continent" => "Europe", "continent_code" => "EU", "id" => "150"),
    "MS" => array("name" => "Montserrat", "phone" => "1664", "continent" => "North America", "continent_code" => "NA", "id" => "151"),
    "MA" => array("name" => "Morocco", "phone" => "212", "continent" => "Africa", "continent_code" => "AF", "id" => "152"),
    "MZ" => array("name" => "Mozambique", "phone" => "258", "continent" => "Africa", "continent_code" => "AF", "id" => "153"),
    "MM" => array("name" => "Myanmar", "phone" => "95", "continent" => "Asia", "continent_code" => "AS", "id" => "154"),
    "NA" => array("name" => "Namibia", "phone" => "264", "continent" => "Africa", "continent_code" => "AF", "id" => "155"),
    "NR" => array("name" => "Nauru", "phone" => "674", "continent" => "Oceania", "continent_code" => "OC", "id" => "156"),
    "NP" => array("name" => "Nepal", "phone" => "977", "continent" => "Asia", "continent_code" => "AS", "id" => "157"),
    "NL" => array("name" => "Netherlands", "phone" => "31", "continent" => "Europe", "continent_code" => "EU", "id" => "158"),
    "AN" => array("name" => "Netherlands Antilles", "phone" => "599", "continent" => "North America", "continent_code" => "NA", "id" => "159"),
    "NC" => array("name" => "New Caledonia", "phone" => "687", "continent" => "Oceania", "continent_code" => "OC", "id" => "160"),
    "NZ" => array("name" => "New Zealand", "phone" => "64", "continent" => "Oceania", "continent_code" => "OC", "id" => "161"),
    "NI" => array("name" => "Nicaragua", "phone" => "505", "continent" => "North America", "continent_code" => "NA", "id" => "162"),
    "NE" => array("name" => "Niger", "phone" => "227", "continent" => "Africa", "continent_code" => "AF", "id" => "163"),
    "NG" => array("name" => "Nigeria", "phone" => "234", "continent" => "Africa", "continent_code" => "AF", "id" => "164"),
    "NU" => array("name" => "Niue", "phone" => "683", "continent" => "Oceania", "continent_code" => "OC", "id" => "165"),
    "NF" => array("name" => "Norfolk Island", "phone" => "672", "continent" => "Oceania", "continent_code" => "OC", "id" => "166"),
    "MP" => array("name" => "Northern Mariana Islands", "phone" => "1670", "continent" => "Oceania", "continent_code" => "OC", "id" => "167"),
    "NO" => array("name" => "Norway", "phone" => "47", "continent" => "Europe", "continent_code" => "EU", "id" => "168"),
    "OM" => array("name" => "Oman", "phone" => "968", "continent" => "Asia", "continent_code" => "AS", "id" => "169"),
    "PK" => array("name" => "Pakistan", "phone" => "92", "continent" => "Asia", "continent_code" => "AS", "id" => "170"),
    "PW" => array("name" => "Palau", "phone" => "680", "continent" => "Oceania", "continent_code" => "OC", "id" => "171"),
    "PS" => array("name" => "Palestinian Territory, Occupied", "phone" => "970", "continent" => "Asia", "continent_code" => "AS", "id" => "172"),
    "PA" => array("name" => "Panama", "phone" => "507", "continent" => "North America", "continent_code" => "NA", "id" => "173"),
    "PG" => array("name" => "Papua New Guinea", "phone" => "675", "continent" => "Oceania", "continent_code" => "OC", "id" => "174"),
    "PY" => array("name" => "Paraguay", "phone" => "595", "continent" => "South America", "continent_code" => "SA", "id" => "175"),
    "PE" => array("name" => "Peru", "phone" => "51", "continent" => "South America", "continent_code" => "SA", "id" => "176"),
    "PH" => array("name" => "Philippines", "phone" => "63", "continent" => "Asia", "continent_code" => "AS", "id" => "177"),
    "PN" => array("name" => "Pitcairn", "phone" => "64", "continent" => "Oceania", "continent_code" => "OC", "id" => "178"),
    "PL" => array("name" => "Poland", "phone" => "48", "continent" => "Europe", "continent_code" => "EU", "id" => "179"),
    "PT" => array("name" => "Portugal", "phone" => "351", "continent" => "Europe", "continent_code" => "EU", "id" => "180"),
    "PR" => array("name" => "Puerto Rico", "phone" => "1787", "continent" => "North America", "continent_code" => "NA", "id" => "181"),
    "QA" => array("name" => "Qatar", "phone" => "974", "continent" => "Asia", "continent_code" => "AS", "id" => "182"),
    "RE" => array("name" => "Reunion", "phone" => "262", "continent" => "Africa", "continent_code" => "AF", "id" => "183"),
    "RO" => array("name" => "Romania", "phone" => "40", "continent" => "Europe", "continent_code" => "EU", "id" => "184"),
    "RU" => array("name" => "Russian Federation", "phone" => "70", "continent" => "Asia", "continent_code" => "AS", "id" => "185"),
    "RW" => array("name" => "Rwanda", "phone" => "250", "continent" => "Africa", "continent_code" => "AF", "id" => "186"),
    "BL" => array("name" => "Saint Barthelemy", "phone" => "590", "continent" => "North America", "continent_code" => "NA", "id" => "187"),
    "SH" => array("name" => "Saint Helena", "phone" => "290", "continent" => "Africa", "continent_code" => "AF", "id" => "188"),
    "KN" => array("name" => "Saint Kitts and Nevis", "phone" => "1869", "continent" => "North America", "continent_code" => "NA", "id" => "189"),
    "LC" => array("name" => "Saint Lucia", "phone" => "1758", "continent" => "North America", "continent_code" => "NA", "id" => "190"),
    "MF" => array("name" => "Saint Martin", "phone" => "590", "continent" => "North America", "continent_code" => "NA", "id" => "191"),
    "PM" => array("name" => "Saint Pierre and Miquelon", "phone" => "508", "continent" => "North America", "continent_code" => "NA", "id" => "192"),
    "VC" => array("name" => "Saint Vincent and the Grenadines", "phone" => "1784", "continent" => "North America", "continent_code" => "NA", "id" => "193"),
    "WS" => array("name" => "Samoa", "phone" => "684", "continent" => "Oceania", "continent_code" => "OC", "id" => "194"),
    "SM" => array("name" => "San Marino", "phone" => "378", "continent" => "Europe", "continent_code" => "EU", "id" => "195"),
    "ST" => array("name" => "Sao Tome and Principe", "phone" => "239", "continent" => "Africa", "continent_code" => "AF", "id" => "196"),
    "SA" => array("name" => "Saudi Arabia", "phone" => "966", "continent" => "Asia", "continent_code" => "AS", "id" => "197"),
    "SN" => array("name" => "Senegal", "phone" => "221", "continent" => "Africa", "continent_code" => "AF", "id" => "198"),
    "RS" => array("name" => "Serbia", "phone" => "381", "continent" => "Europe", "continent_code" => "EU", "id" => "199"),
    "CS" => array("name" => "Serbia and Montenegro", "phone" => "381", "continent" => "Europe", "continent_code" => "EU", "id" => "200"),
    "SC" => array("name" => "Seychelles", "phone" => "248", "continent" => "Africa", "continent_code" => "AF", "id" => "201"),
    "SL" => array("name" => "Sierra Leone", "phone" => "232", "continent" => "Africa", "continent_code" => "AF", "id" => "202"),
    "SG" => array("name" => "Singapore", "phone" => "65", "continent" => "Asia", "continent_code" => "AS", "id" => "203"),
    "SX" => array("name" => "Sint Maarten", "phone" => "1", "continent" => "North America", "continent_code" => "NA", "id" => "204"),
    "SK" => array("name" => "Slovakia", "phone" => "421", "continent" => "Europe", "continent_code" => "EU", "id" => "205"),
    "SI" => array("name" => "Slovenia", "phone" => "386", "continent" => "Europe", "continent_code" => "EU", "id" => "206"),
    "SB" => array("name" => "Solomon Islands", "phone" => "677", "continent" => "Oceania", "continent_code" => "OC", "id" => "207"),
    "SO" => array("name" => "Somalia", "phone" => "252", "continent" => "Africa", "continent_code" => "AF", "id" => "208"),
    "ZA" => array("name" => "South Africa", "phone" => "27", "continent" => "Africa", "continent_code" => "AF", "id" => "209"),
    "GS" => array("name" => "South Georgia and the South Sandwich Islands", "phone" => "500", "continent" => "Antarctica", "continent_code" => "AN", "id" => "210"),
    "SS" => array("name" => "South Sudan", "phone" => "211", "continent" => "Africa", "continent_code" => "AF", "id" => "211"),
    "ES" => array("name" => "Spain", "phone" => "34", "continent" => "Europe", "continent_code" => "EU", "id" => "212"),
    "LK" => array("name" => "Sri Lanka", "phone" => "94", "continent" => "Asia", "continent_code" => "AS", "id" => "213"),
    "SD" => array("name" => "Sudan", "phone" => "249", "continent" => "Africa", "continent_code" => "AF", "id" => "214"),
    "SR" => array("name" => "Suriname", "phone" => "597", "continent" => "South America", "continent_code" => "SA", "id" => "215"),
    "SJ" => array("name" => "Svalbard and Jan Mayen", "phone" => "47", "continent" => "Europe", "continent_code" => "EU", "id" => "216"),
    "SZ" => array("name" => "Swaziland", "phone" => "268", "continent" => "Africa", "continent_code" => "AF", "id" => "217"),
    "SE" => array("name" => "Sweden", "phone" => "46", "continent" => "Europe", "continent_code" => "EU", "id" => "218"),
    "CH" => array("name" => "Switzerland", "phone" => "41", "continent" => "Europe", "continent_code" => "EU", "id" => "219"),
    "SY" => array("name" => "Syrian Arab Republic", "phone" => "963", "continent" => "Asia", "continent_code" => "AS", "id" => "220"),
    "TW" => array("name" => "Taiwan, Province of China", "phone" => "886", "continent" => "Asia", "continent_code" => "AS", "id" => "221"),
    "TJ" => array("name" => "Tajikistan", "phone" => "992", "continent" => "Asia", "continent_code" => "AS", "id" => "222"),
    "TZ" => array("name" => "Tanzania, United Republic of", "phone" => "255", "continent" => "Africa", "continent_code" => "AF", "id" => "223"),
    "TH" => array("name" => "Thailand", "phone" => "66", "continent" => "Asia", "continent_code" => "AS", "id" => "224"),
    "TL" => array("name" => "Timor-Leste", "phone" => "670", "continent" => "Asia", "continent_code" => "AS", "id" => "225"),
    "TG" => array("name" => "Togo", "phone" => "228", "continent" => "Africa", "continent_code" => "AF", "id" => "226"),
    "TK" => array("name" => "Tokelau", "phone" => "690", "continent" => "Oceania", "continent_code" => "OC", "id" => "227"),
    "TO" => array("name" => "Tonga", "phone" => "676", "continent" => "Oceania", "continent_code" => "OC", "id" => "228"),
    "TT" => array("name" => "Trinidad and Tobago", "phone" => "1868", "continent" => "North America", "continent_code" => "NA", "id" => "229"),
    "TN" => array("name" => "Tunisia", "phone" => "216", "continent" => "Africa", "continent_code" => "AF", "id" => "230"),
    "TR" => array("name" => "Turkey", "phone" => "90", "continent" => "Asia", "continent_code" => "AS", "id" => "231"),
    "TM" => array("name" => "Turkmenistan", "phone" => "7370", "continent" => "Asia", "continent_code" => "AS", "id" => "232"),
    "TC" => array("name" => "Turks and Caicos Islands", "phone" => "1649", "continent" => "North America", "continent_code" => "NA", "id" => "233"),
    "TV" => array("name" => "Tuvalu", "phone" => "688", "continent" => "Oceania", "continent_code" => "OC", "id" => "234"),
    "UG" => array("name" => "Uganda", "phone" => "256", "continent" => "Africa", "continent_code" => "AF", "id" => "235"),
    "UA" => array("name" => "Ukraine", "phone" => "380", "continent" => "Europe", "continent_code" => "EU", "id" => "236"),
    "AE" => array("name" => "United Arab Emirates", "phone" => "971", "continent" => "Asia", "continent_code" => "AS", "id" => "237"),
    "GB" => array("name" => "United Kingdom", "phone" => "44", "continent" => "Europe", "continent_code" => "EU", "id" => "238"),
    "US" => array("name" => "United States", "phone" => "1", "continent" => "North America", "continent_code" => "NA", "id" => "239"),
    "UM" => array("name" => "United States Minor Outlying Islands", "phone" => "1", "continent" => "North America", "continent_code" => "NA", "id" => "240"),
    "UY" => array("name" => "Uruguay", "phone" => "598", "continent" => "South America", "continent_code" => "SA", "id" => "241"),
    "UZ" => array("name" => "Uzbekistan", "phone" => "998", "continent" => "Asia", "continent_code" => "AS", "id" => "242"),
    "VU" => array("name" => "Vanuatu", "phone" => "678", "continent" => "Oceania", "continent_code" => "OC", "id" => "243"),
    "VE" => array("name" => "Venezuela", "phone" => "58", "continent" => "South America", "continent_code" => "SA", "id" => "244"),
    "VN" => array("name" => "Viet Nam", "phone" => "84", "continent" => "Asia", "continent_code" => "AS", "id" => "245"),
    "VG" => array("name" => "Virgin Islands, British", "phone" => "1284", "continent" => "North America", "continent_code" => "NA", "id" => "246"),
    "VI" => array("name" => "Virgin Islands, U.s.", "phone" => "1340", "continent" => "North America", "continent_code" => "NA", "id" => "247"),
    "WF" => array("name" => "Wallis and Futuna", "phone" => "681", "continent" => "Oceania", "continent_code" => "OC", "id" => "248"),
    "EH" => array("name" => "Western Sahara", "phone" => "212", "continent" => "Africa", "continent_code" => "AF", "id" => "249"),
    "YE" => array("name" => "Yemen", "phone" => "967", "continent" => "Asia", "continent_code" => "AS", "id" => "250"),
    "ZM" => array("name" => "Zambia", "phone" => "260", "continent" => "Africa", "continent_code" => "AF", "id" => "251"),
    "ZW" => array("name" => "Zimbabwe", "phone" => "263", "continent" => "Africa", "continent_code" => "AF", "id" => "252")
);
?>